### ISSUE TITLE
CMD Terminal window opens with the application

### ISSUE THREAD

**Issue by S0RC3RER** [TheMrNomnom/FFMpeg_Audio_Image_Joiner#4]
A blank CMD terminal window opens with the application that displays the output of running the FFmpeg command.

**Comment by S0RC3RER** [comment]
The behavior occurs due to PyInstaller. I'll add the `--noconsole` [flag](https://pyinstaller.org/en/stable/usage.html#cmdoption-w) when converting to EXE for next version.

**Comment by TheMrNomnom** [comment]
This behavior is due to using PyInstaller to make the application into an executable. I'll add the `--noconsole` [flag](https://pyinstaller.org/en/stable/usage.html#cmdoption-w) for the next version.
